### ISSUE TITLE
gerber files for updated reviung?

### ISSUE THREAD

**Issue by aslvrstn** [idank/keyboards#2]
looks like https://github.com/idank/keyboards/commit/459c026e78a73bd3fcf2d31e9ef57dc7914e352d removed the gerber files for the reviungs. just wondering if that was deliberate or an oversight. thanks!

**Comment by idank** [comment]
They were likely out of date. This repo only has source files, please create the gerber files yourself (I recommend the Fabrication Toolkit plugin).

p.s. holykeebs.com will soon have an option to buy kits.
